raw_reads_dir: emseq/o38437_NovaSeq_250620_X288/
data_dir: data
output_dir: results
logs_dir: logs
benchmarks_dir: benchmarks


genome_url: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"